# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-18.04"
        
    config.vm.provision "shell", inline: <<-SHELL
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    apt-get -qq update
    apt-get install -y puppet-agent
    SHELL

    config.vm.provision "puppet" do |puppet|
        puppet.environment = "test"
        puppet.environment_path = "environments"
        puppet.module_path = "modules"
    end

    config.vm.define "proxy" do |proxy|
        proxy.vm.hostname = "proxy"
        ENV['proxy_ip'] = {inline: }
        # run redis
    end

    # set environment variable 
    
end
