# -*- mode: ruby -*-
# vi: set ft=ruby :

tst = Integer(ENV['tst']) || 2

Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-18.04"
        
    config.vm.provision "shell", inline: <<-SHELL
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    apt-get -qq update
    apt-get install -y puppet-agent
    SHELL

    config.vm.provision "puppet" do |puppet|
        puppet.environment = "test"
        puppet.environment_path = "environments"
        puppet.module_path = "modules"
    end

    # config.vm.define "appserver" do |appserver|
    #     appserver.vm.hostname = "appserver"
    # end
    
    config.vm.define "dbserver" do |dbserver|
        dbserver.vm.hostname = "dbserver"
    end

    config.vm.define "web" do |web|
        web.vm.hostname = "web"
        web.vm.network "forwarded_port", guest: 80, host: 8080
    end
    
    # (0..tst-1).each do |i|
    #     config.vm.define "tst#{i}" do |testserver|
    #        testserver.vm.hostname = "tst#{i}"
    #     end
    # end
end
